from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from passlib.context import CryptContext
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.database import Base, SessionLocal, engine
from app.models.category import Category
from app.models.complaint import Complaint
from app.models.department import Department
from app.models.user import User

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

OFFICIAL_DEPARTMENTS = [
    {
        "name": "مديرية الخدمات المحلية",
        "slug": "services-local",
        "description": "النفايات، النظافة، الحدائق، الأرصفة، الإنارة، الحفر، والخدمات اليومية.",
        "scope": "directorate",
    },
    {
        "name": "مديريات المجالس المحلية والإدارة المحلية",
        "slug": "local-councils-admin",
        "description": "متابعة أداء الوحدات الإدارية، شكاوى المواطنين المتعلقة بالإدارة المحلية، ومتابعة المجالس المحلية.",
        "scope": "directorate",
    },
    {
        "name": "مديرية التخطيط والتنمية المحلية",
        "slug": "planning-local-development",
        "description": "تحديد احتياجات المناطق، ترتيب الأولويات، ومتابعة المشاريع والتنمية المحلية.",
        "scope": "directorate",
    },
    {
        "name": "مديرية التنظيم والتخطيط العمراني",
        "slug": "urban-planning",
        "description": "مشاكل التنظيم، البناء، الطرق المرتبطة بالتنظيم العمراني، استعمالات الأراضي، والمخططات التنظيمية.",
        "scope": "directorate",
    },
    {
        "name": "مديرية الشؤون الفنية",
        "slug": "technical-affairs",
        "description": "المشاريع الخدمية، البنية التحتية، الصيانة الفنية، ومتابعة تنفيذ المشاريع.",
        "scope": "directorate",
    },
    {
        "name": "مديرية الشؤون المالية",
        "slug": "financial-affairs",
        "description": "الموازنات المحلية، الإيرادات، النفقات، ومتابعة الموارد والقضايا المالية المحلية.",
        "scope": "directorate",
    },
    {
        "name": "مديرية الرقابة والتفتيش",
        "slug": "inspection-audit",
        "description": "متابعة الشكاوى، المخالفات، مراقبة أداء الجهات المحلية، والتقصير الإداري.",
        "scope": "directorate",
    },
    {
        "name": "المحافظات",
        "slug": "governorates",
        "description": "استقبال ومتابعة المشاكل على مستوى المحافظة، وتنسيق الحلول بين الجهات.",
        "scope": "governorate",
    },
    {
        "name": "مجالس المدن والبلديات والوحدات الإدارية",
        "slug": "municipal-local-units",
        "description": "الجهة التنفيذية الأقرب للمواطن، الخدمات اليومية المحلية، ومتابعة العيوب المباشرة داخل الوحدة الإدارية.",
        "scope": "local_unit",
    },
]

SEED_CATEGORIES = [
    ("نفايات ونظافة", "waste-sanitation", "القمامة والتراكم والبيئة"),
    ("حدائق", "parks", "المساحات الخضراء والحدائق العامة"),
    ("أرصفة", "sidewalks", "أرصفة وممرات المشاة"),
    ("إنارة", "lighting", "أعمدة الإنارة والأنوار العامة"),
    ("حفر وطرق محلية", "potholes-local-roads", "حفرة ومشكلات الطرق المحلية"),
    ("خدمات يومية", "daily-services", "الخدمات اليومية والعيوب التشغيلية"),
    ("شكوى على وحدة إدارية", "complaint-against-unit", "تدني الخدمة أو التأخر في الوحدة الإدارية"),
    ("أداء جهة محلية", "local-entity-performance", "أداء الجهة المحلية"),
    ("احتياجات منطقة", "area-needs", "احتياجات المنطقة والمشاريع اللازمة"),
    ("أولوية مشروع خدمي", "service-project-priority", "أولوية مشاريع الخدمات"),
    ("تنظيم عمراني", "urban-planning", "تنظيم عمراني ومخططات"),
    ("مخالفة بناء", "building-violation", "مخالفة بناء أو توسع غير مرخص"),
    ("استعمالات أراضٍ", "land-use", "استعمالات الأراضي"),
    ("طرق وتنظيم", "roads-urban-regulation", "طرق وتخطيط عام"),
    ("مشروع خدمي", "service-project", "مشروع خدمي يحتاج تنفيذ"),
    ("بنية تحتية", "infrastructure", "بنية تحتية وشبكات"),
    ("صيانة", "maintenance", "صيانة فنية ومشاكل تشغيلية"),
    ("موازنة محلية", "local-budget", "الموازنة والمالية المحلية"),
    ("إيرادات ونفقات", "revenues-expenses", "إيرادات ونفقات"),
    ("موارد محلية", "local-resources", "موارد محلية"),
    ("مخالفة إدارية", "administrative-violation", "مخالفة إدارية أو خرق أنظمة"),
    ("شكوى رقابية", "oversight-complaint", "شكوى رقابية أو متابعة"),
    ("تقصير جهة محلية", "local-entity-shortfall", "تقصير جهة محلية"),
    ("مشكلة على مستوى المحافظة", "governorate-level-problem", "مشكل على مستوى المحافظة"),
    ("مشكلة بلدية محلية", "municipal-local-problem", "مشكلة بلدية مباشرة"),
    ("أخرى", "other", "فئة أخرى غير مصنفة"),
]

DEMO_COMPLAINTS = [
    {
        "title": "تراكم نفايات في حي العزيزية",
        "description": "تراكمت النفايات في ممرات الحي وبدأت رائحة كريهة تؤثر على السكان.",
        "address": "حي العزيزية، شارع 7",
        "area": "الحي الشرقي",
        "governorate": "عمان",
        "latitude": 31.9539,
        "longitude": 35.9106,
        "category": "نفايات ونظافة",
        "priority": "high",
        "status": "new",
        "department": "مديرية الخدمات المحلية",
        "routing_reason": "تم التوجيه إلى مديرية الخدمات المحلية لأن البلاغ متعلق بتراكم النفايات والنظافة.",
        "routing_confidence": 0.96,
    },
    {
        "title": "عطل في عمود الإنارة في شارع النخيل",
        "description": "توقفت إنارة أحد الشوارع الرئيسية، مما يهدد السلامة في المساء.",
        "address": "شارع النخيل، قرب الساحة",
        "area": "الرمل",
        "governorate": "عمان",
        "latitude": 31.9583,
        "longitude": 35.9251,
        "category": "إنارة",
        "priority": "high",
        "status": "assigned",
        "department": "مديرية الخدمات المحلية",
        "routing_reason": "تم التوجيه إلى مديرية الخدمات المحلية لأن البلاغ متعلق بإنارة عامة معطلة.",
        "routing_confidence": 0.92,
    },
    {
        "title": "حفرة كبيرة في الطريق أمام المدرسة",
        "description": "توجد حفرة عميقة تؤثر على حركة السيارات والمشاة بالقرب من المدرسة.",
        "address": "الشارع الرئيسي، أمام المدرسة الثانوية",
        "area": "المنطقة الوسطى",
        "governorate": "البلقاء",
        "latitude": 32.0895,
        "longitude": 35.9125,
        "category": "حفر وطرق محلية",
        "priority": "urgent",
        "status": "in_progress",
        "department": "مديرية الخدمات المحلية",
        "routing_reason": "تم التوجيه إلى مديرية الخدمات المحلية لأن البلاغ يتعلق بحفرة وطرق محلية تحتاج تدخل فوري.",
        "routing_confidence": 0.97,
    },
    {
        "title": "رصيف متضرر في شارع السعادة",
        "description": "الرصيف مكسور في أكثر من موقع ويشكل خطرًا للمشاة.",
        "address": "شارع السعادة، حي النزهة",
        "area": "حي النزهة",
        "governorate": "عمان",
        "latitude": 31.9404,
        "longitude": 35.8866,
        "category": "أرصفة",
        "priority": "high",
        "status": "new",
        "department": "مديرية الخدمات المحلية",
        "routing_reason": "تم التوجيه إلى مديرية الخدمات المحلية لأن البلاغ متعلق برصيف متضرر يحتاج صيانة.",
        "routing_confidence": 0.91,
    },
    {
        "title": "تأخر الوحدة الإدارية في معالجة طلبات المقيمين",
        "description": "تأخر فريق الوحدة الإدارية في الرد على طلبات الصيانة ورفع العيوب في الحي.",
        "address": "وحدة حي الوادي",
        "area": "حي الوادي",
        "governorate": "عمان",
        "latitude": 31.9677,
        "longitude": 35.8718,
        "category": "شكوى على وحدة إدارية",
        "priority": "medium",
        "status": "assigned",
        "department": "مديريات المجالس المحلية والإدارة المحلية",
        "routing_reason": "تم التوجيه إلى مديريات المجالس المحلية والإدارة المحلية لأن البلاغ يتعلق بأداء الوحدة الإدارية وتقصيرها في المتابعة.",
        "routing_confidence": 0.94,
    },
    {
        "title": "المنطقة تحتاج مشروع خدمياً جديداً بسبب النمو السكاني",
        "description": "ازداد عدد السكان في المنطقة دون زيادة في الخدمات الأساسية مثل المياه والحدائق.",
        "address": "حي السهيلة",
        "area": "المنطقة الشرقية",
        "governorate": "الزرقاء",
        "latitude": 32.0674,
        "longitude": 36.0949,
        "category": "احتياجات منطقة",
        "priority": "high",
        "status": "new",
        "department": "مديرية التخطيط والتنمية المحلية",
        "routing_reason": "تم التوجيه إلى مديرية التخطيط والتنمية المحلية لأن البلاغ يصف احتياجاً من احتياجات المنطقة وتحديد أولويات المشاريع.",
        "routing_confidence": 0.9,
    },
    {
        "title": "أولوية مشروع خدمي لمجمع خدمية للباحثين",
        "description": "المنطقة تعاني من نقص في مرافق المرافق الخدمية، ويحتاج المشروع إلى دعم تنموي.",
        "address": "ضاحية الضليعة",
        "area": "الضليعة",
        "governorate": "إربد",
        "latitude": 32.5556,
        "longitude": 35.8518,
        "category": "أولوية مشروع خدمي",
        "priority": "high",
        "status": "new",
        "department": "مديرية التخطيط والتنمية المحلية",
        "routing_reason": "تم التوجيه إلى مديرية التخطيط والتنمية المحلية لأن البلاغ يتعلق بأولوية مشروع خدمية وتنمية محلية.",
        "routing_confidence": 0.88,
    },
    {
        "title": "مخالفة بناء في أرض سكنية",
        "description": "تم بناء طابق إضافي دون تراخيص وفق الأنظمة المعتمدة.",
        "address": "شارع الزهراء، حي البستان",
        "area": "حي البستان",
        "governorate": "عجلون",
        "latitude": 32.2809,
        "longitude": 35.7508,
        "category": "مخالفة بناء",
        "priority": "high",
        "status": "assigned",
        "department": "مديرية التنظيم والتخطيط العمراني",
        "routing_reason": "تم التوجيه إلى مديرية التنظيم والتخطيط العمراني لأن البلاغ يتعلق بمخالفة بناء وتنظيم عمراني.",
        "routing_confidence": 0.96,
    },
    {
        "title": "استخدام أرض لغير الغرض المخصص",
        "description": "تستخدم أرض زراعية في المنطقة بشكل تجاري خلافاً للتخطيط المعتمد.",
        "address": "المنطقة الجنوبية، قرب الطريق الجديد",
        "area": "المنطقة الجنوبية",
        "governorate": "المفرق",
        "latitude": 32.3519,
        "longitude": 35.8320,
        "category": "استعمالات أراضٍ",
        "priority": "medium",
        "status": "new",
        "department": "مديرية التنظيم والتخطيط العمراني",
        "routing_reason": "تم التوجيه إلى مديرية التنظيم والتخطيط العمراني لأن البلاغ متعلق باستعمالات الأراضي وتخطيط العمران.",
        "routing_confidence": 0.9,
    },
    {
        "title": "تضرر شبكة البنية التحتية في الحي",
        "description": "تضررت شبكة المياه والأراضي المبطنة في القطاعات الرئيسية وتمت ملاحظة تسرب متكرر.",
        "address": "حي الروضة، شارع 12",
        "area": "حي الروضة",
        "governorate": "عمان",
        "latitude": 31.9162,
        "longitude": 35.9242,
        "category": "بنية تحتية",
        "priority": "urgent",
        "status": "in_progress",
        "department": "مديرية الشؤون الفنية",
        "routing_reason": "تم التوجيه إلى مديرية الشؤون الفنية لأن البلاغ متعلق بضرر في البنية التحتية واحتياج إلى صيانة فنية.",
        "routing_confidence": 0.95,
    },
    {
        "title": "تلف في شبكة الصرف الصحي بموقع تجاري",
        "description": "تسرب مياه صرف صحي يؤثر على المارة ويجب معالجة فورية.",
        "address": "المنطقة التجارية، شارع القدس",
        "area": "المنطقة التجارية",
        "governorate": "السلط",
        "latitude": 32.0403,
        "longitude": 35.7264,
        "category": "صيانة",
        "priority": "urgent",
        "status": "assigned",
        "department": "مديرية الشؤون الفنية",
        "routing_reason": "تم التوجيه إلى مديرية الشؤون الفنية لأن البلاغ يتناول صيانة فنية في شبكة الصرف الصحي.",
        "routing_confidence": 0.94,
    },
    {
        "title": "شكوى مرتبطة برسوم محلية ومورد محلي",
        "description": "توجد ملاحظات على زيادة الرسوم المحلية وعدم شفافيتها في التنفيذ.",
        "address": "مركز المدينة",
        "area": "المدينة",
        "governorate": "جرش",
        "latitude": 32.2802,
        "longitude": 35.8961,
        "category": "إيرادات ونفقات",
        "priority": "medium",
        "status": "new",
        "department": "مديرية الشؤون المالية",
        "routing_reason": "تم التوجيه إلى مديرية الشؤون المالية لأن البلاغ يتعلق بموازنات محلية وإيرادات ونفقات.",
        "routing_confidence": 0.91,
    },
    {
        "title": "مطالبة بتحسين مراقبة الموارد المحلية",
        "description": "يوجد قلق بشأن عدم استخدام الموارد المحلية بالشكل الأمثل في المنطقة.",
        "address": "حي المحطة",
        "area": "حي المحطة",
        "governorate": "الكرك",
        "latitude": 31.1808,
        "longitude": 35.7030,
        "category": "موارد محلية",
        "priority": "medium",
        "status": "new",
        "department": "مديرية الشؤون المالية",
        "routing_reason": "تم التوجيه إلى مديرية الشؤون المالية لأن البلاغ يتعلق بموارد محلية ومتابعة الإنفاق.",
        "routing_confidence": 0.86,
    },
    {
        "title": "تقصير جهة محلية في متابعة طلبات المياه",
        "description": "تم تسجيل عدد من طلبات المياه دون متابعة كافية من الجهة المحلية المعنية.",
        "address": "حي الناصرة",
        "area": "حي الناصرة",
        "governorate": "الرمثا",
        "latitude": 32.5615,
        "longitude": 35.8441,
        "category": "تقصير جهة محلية",
        "priority": "high",
        "status": "assigned",
        "department": "مديرية الرقابة والتفتيش",
        "routing_reason": "تم التوجيه إلى مديرية الرقابة والتفتيش لأن البلاغ يتعلق بتقصير جهة محلية ومتابعة الأداء.",
        "routing_confidence": 0.94,
    },
    {
        "title": "مخالفة إدارية في تقديم الخدمة",
        "description": "توجد مخالفة إدارية في التعامل مع الخدمات العامة وعدم الالتزام بالإجراءات.",
        "address": "مبنى البلدية المركزي",
        "area": "مركز البلدة",
        "governorate": "مادبا",
        "latitude": 31.7298,
        "longitude": 35.7930,
        "category": "مخالفة إدارية",
        "priority": "medium",
        "status": "new",
        "department": "مديرية الرقابة والتفتيش",
        "routing_reason": "تم التوجيه إلى مديرية الرقابة والتفتيش لأن البلاغ يخص مخالفة إدارية ومتابعة الأداء.",
        "routing_confidence": 0.93,
    },
    {
        "title": "شكوى رقابية على أداء البلدية",
        "description": "تستفسر الأسرة عن ممارسات البلدية في التعامل مع طلبات الرفع والتشغيل.",
        "address": "مركز البلدية",
        "area": "المركز",
        "governorate": "البادية الشمالية",
        "latitude": 30.1834,
        "longitude": 35.7276,
        "category": "شكوى رقابية",
        "priority": "high",
        "status": "assigned",
        "department": "مديرية الرقابة والتفتيش",
        "routing_reason": "تم التوجيه إلى مديرية الرقابة والتفتيش لأنها الجهة المختصة في متابعة الشكاوى الرقابية وأداء الجهات المحلية.",
        "routing_confidence": 0.9,
    },
    {
        "title": "مشكلة خدمية تشمل أكثر من بلدية وتحتاج تنسيقاً",
        "description": "تتجاوز المشكلة حدود دائرة واحدة وتحتاج تنسيقاً بين أكثر من جهة محلية.",
        "address": "منطقة الوصل بين البلديات",
        "area": "الحدود بين البلديات",
        "governorate": "الطفيلة",
        "latitude": 30.8337,
        "longitude": 35.6152,
        "category": "مشكلة على مستوى المحافظة",
        "priority": "urgent",
        "status": "in_progress",
        "department": "المحافظات",
        "routing_reason": "تم التوجيه إلى المحافظات لأن المشكلة تتجاوز حدود جهة واحدة وتحتاج تنسيقاً على مستوى المحافظة.",
        "routing_confidence": 0.97,
    },
    {
        "title": "تبرز مشكلة في الحديقة العامة في حي واحد",
        "description": "الحديقة بحاجة إلى صيانة مباشرة وتهيئة غير متوفرة في الوقت الحالي.",
        "address": "حديقة النخيل، حي النخيل",
        "area": "حي النخيل",
        "governorate": "معان",
        "latitude": 30.1919,
        "longitude": 35.6024,
        "category": "حدائق",
        "priority": "medium",
        "status": "new",
        "department": "مجالس المدن والبلديات والوحدات الإدارية",
        "routing_reason": "تم التوجيه إلى مجالس المدن والبلديات والوحدات الإدارية لأن المشكلة مباشرة في حي محدد وتحتاج تنفيذ محلي.",
        "routing_confidence": 0.9,
    },
    {
        "title": "بلوك انقطاع مياه في حي الروضة",
        "description": "لا يوجد توفر كافي للمياه في أجزاء الحي وقد تم تقديم الطلب عدة مرات.",
        "address": "حي الروضة، شارع 9",
        "area": "حي الروضة",
        "governorate": "السلط",
        "latitude": 32.0410,
        "longitude": 35.7205,
        "category": "خدمات يومية",
        "priority": "high",
        "status": "assigned",
        "department": "مجالس المدن والبلديات والوحدات الإدارية",
        "routing_reason": "تم التوجيه إلى مجالس المدن والبلديات والوحدات الإدارية لأن البلاغ يتعلق بخدمة يومية مباشرة ضمن الوحدة الإدارية.",
        "routing_confidence": 0.93,
    },
    {
        "title": "تسرب في شبكة المياه في منطقة السكن",
        "description": "تسرب مستمر في شبكة المياه يسبب أضرارًا في المنازل القريبة.",
        "address": "حي السكن الجديد",
        "area": "السكن الجديد",
        "governorate": "الزرقاء",
        "latitude": 32.0745,
        "longitude": 36.0913,
        "category": "خدمات يومية",
        "priority": "urgent",
        "status": "in_progress",
        "department": "مجالس المدن والبلديات والوحدات الإدارية",
        "routing_reason": "تم التوجيه إلى مجالس المدن والبلديات والوحدات الإدارية لأن البلاغ يتطلب تنفيذًا محليًا سريعًا.",
        "routing_confidence": 0.92,
    },
    {
        "title": "تجاوزات في تنظيم الطريق داخل الحي",
        "description": "توجد أضرار في رصف الطريق بجانب أرصفة وأماكن انتظار غير مرتبة.",
        "address": "حي الفارسية",
        "area": "حي الفارسية",
        "governorate": "عمان",
        "latitude": 31.9865,
        "longitude": 35.9524,
        "category": "طرق وتنظيم",
        "priority": "medium",
        "status": "new",
        "department": "مديرية التنظيم والتخطيط العمراني",
        "routing_reason": "تم التوجيه إلى مديرية التنظيم والتخطيط العمراني لأن البلاغ يتعلق بالطرق والتنظيم العمراني.",
        "routing_confidence": 0.87,
    },
    {
        "title": "مشروع خدمي يحتاج تنفيذ سريع في الحي",
        "description": "الحارة تعاني من نقص في الخدمات الأساسية وهنا يطلب تنفيذ مشروع خدمية جديد.",
        "address": "حي المروج",
        "area": "حي المروج",
        "governorate": "إربد",
        "latitude": 32.5548,
        "longitude": 35.8451,
        "category": "مشروع خدمي",
        "priority": "high",
        "status": "assigned",
        "department": "مديرية التخطيط والتنمية المحلية",
        "routing_reason": "تم التوجيه إلى مديرية التخطيط والتنمية المحلية لأن البلاغ يخص مشروع خدمية يحتاج تنسيقاً وتنفيذًا.",
        "routing_confidence": 0.9,
    },
    {
        "title": "مشكلة بلدية محلية في صيانة الحديقة",
        "description": "الحديقة المحلية في الحي هي بحاجة إلى صيانة فورية من البلديّة.",
        "address": "حديقة الكرامة",
        "area": "المدينة",
        "governorate": "الكرك",
        "latitude": 31.1824,
        "longitude": 35.7085,
        "category": "مشكلة بلدية محلية",
        "priority": "medium",
        "status": "new",
        "department": "مجالس المدن والبلديات والوحدات الإدارية",
        "routing_reason": "تم التوجيه إلى مجالس المدن والبلديات والوحدات الإدارية لأن البلاغ مشكلة محلية مباشرة تحتاج التنفيذ المحلي.",
        "routing_confidence": 0.91,
    },
    {
        "title": "طلب للتنظيم في منطقة سكنية جديدة",
        "description": "المنطقة تعرف بالازدحام ومشكلات تنظيمية في الشوارع والإنارة.",
        "address": "حي الشروق",
        "area": "حي الشروق",
        "governorate": "البلقاء",
        "latitude": 32.0872,
        "longitude": 35.9011,
        "category": "تنظيم عمراني",
        "priority": "medium",
        "status": "new",
        "department": "مديرية التنظيم والتخطيط العمراني",
        "routing_reason": "تم التوجيه إلى مديرية التنظيم والتخطيط العمراني لأن البلاغ يتعلق بالتنظيم العمراني.",
        "routing_confidence": 0.89,
    },
    {
        "title": "مشكلة في إضاءة الشوارع الداخلية",
        "description": "بعض الشوارع الداخلية لا تزال مظلمة، مما يعيق الحركة الليلة.",
        "address": "حي البلدة الجديدة",
        "area": "الحي الجديد",
        "governorate": "الرمثا",
        "latitude": 32.5610,
        "longitude": 35.8453,
        "category": "إنارة",
        "priority": "high",
        "status": "new",
        "department": "مديرية الخدمات المحلية",
        "routing_reason": "تم التوجيه إلى مديرية الخدمات المحلية لأن البلاغ متعلق بإنارة عامة داخل حي سكني.",
        "routing_confidence": 0.93,
    },
    {
        "title": "طلب متابعـة الأداء الوحدوي في الحي",
        "description": "يتكرر التأخر في تنفيذ الطلبات المتعلقة بالأرصفة والحدائق.",
        "address": "حي النسيم",
        "area": "حي النسيم",
        "governorate": "معان",
        "latitude": 30.1902,
        "longitude": 35.6047,
        "category": "أداء جهة محلية",
        "priority": "medium",
        "status": "assigned",
        "department": "مديريات المجالس المحلية والإدارة المحلية",
        "routing_reason": "تم التوجيه إلى مديريات المجالس المحلية والإدارة المحلية لأن البلاغ يتعلق بأداء الوحدة الإدارية ومتابعة الأعمال.",
        "routing_confidence": 0.91,
    },
    {
        "title": "مشكلة في إعداد موازنة الحي",
        "description": "توجد ملاحظات على الموازنة المحلية وعدم تناسبها مع الاحتياجات الحالية.",
        "address": "مركز المدينة",
        "area": "المركز",
        "governorate": "جرش",
        "latitude": 32.2825,
        "longitude": 35.8912,
        "category": "موازنة محلية",
        "priority": "medium",
        "status": "new",
        "department": "مديرية الشؤون المالية",
        "routing_reason": "تم التوجيه إلى مديرية الشؤون المالية لأنها الجهة المختصة في الموازنة المحلية والموارد المالية.",
        "routing_confidence": 0.88,
    },
]


def hash_password(password: str) -> str:
    return pwd_context.hash(password)


def seed_data() -> None:
    Base.metadata.create_all(bind=engine)
    db: Session = SessionLocal()
    try:
        if db.query(Category).count() > 0 or db.query(Department).count() > 0:
            return

        departments = [Department(**item) for item in OFFICIAL_DEPARTMENTS]
        db.add_all(departments)
        db.flush()

        for name, slug, description in SEED_CATEGORIES:
            db.add(Category(name=name, slug=slug, description=description))

        citizen = User(
            name="Citizen User",
            email="citizen@example.com",
            hashed_password=hash_password("password"),
            role="citizen",
        )
        admin = User(
            name="Admin User",
            email="admin@example.com",
            hashed_password=hash_password("password"),
            role="admin",
        )
        db.add_all([citizen, admin])
        db.flush()

        department_lookup = {dept.name: dept for dept in departments}
        category_lookup = {
            category.name: category
            for category in db.execute(select(Category)).scalars().all()
        }

        complaint_items = []
        for item in DEMO_COMPLAINTS:
            dept_name = item.get("department")
            category_name = item.get("category")
            complaint_items.append(
                Complaint(
                    user_id=citizen.id,
                    category_id=category_lookup[category_name].id,
                    department_id=department_lookup.get(dept_name).id if dept_name in department_lookup else None,
                    title=item["title"],
                    description=item["description"],
                    address=item.get("address"),
                    area=item.get("area"),
                    governorate=item.get("governorate"),
                    latitude=item.get("latitude"),
                    longitude=item.get("longitude"),
                    priority=item["priority"],
                    status=item["status"],
                    routing_reason=item.get("routing_reason"),
                    routing_confidence=item.get("routing_confidence"),
                    created_at=datetime.now(timezone.utc),
                    updated_at=datetime.now(timezone.utc),
                )
            )

        db.add_all(complaint_items)
        db.commit()
    finally:
        db.close()


if __name__ == "__main__":
    seed_data()
